FROM node:12.18.2-alpine3.11

RUN apk -Uuv add groff less python py-pip
RUN pip install --upgrade awscli
RUN apk --purge -v del py-pip
RUN rm /var/cache/apk/*

RUN apk add -f curl
RUN apk add -f bash

EXPOSE 8080
EXPOSE 9090
EXPOSE 9229